services:
  GPOC0:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8085:8085"
    volumes:
      - ./config:/config
    environment:
      - "spring.config.location=/config/application-docker.yml"
      - IWDB0_ENDPOINT=http://IWDB0:8083
      - CACH0_ENDPOINT=http://CACH0:8082
      - OTPV0_ENDPOINT=http://OTPV0:8087
      - ANSC0_ENDPOINT=http://ANSC0:8081
    image: gpoc-img
    networks:
      - app-net
      
  IWDB0:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    environment:
      - SMOC0_ENDPOINT=http://SMOC0:8089
    image: iwdb-img
    networks:
      - app-net
    volumes:
      - data:/var/lib/h2
  SMOC0:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8089:8089"
    environment:
      - IWDB0_ENDPOINT=http://IWDB0:8083
    image: smoc-img
    networks:
      - app-net      
  ANSC0:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - OTPV0_ENDPOINT=http://OTPV0:8087
    image: ansc-img
    networks:
      - app-net
    volumes:
      - data:/var/lib/h2
  CACH0:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      - OTPV0_ENDPOINT=http://OTPV0:8087
    image: cach-img
    networks:
      - app-net
  OTPV0:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8087:8087"
    environment:
      - CACH0_ENDPOINT=http://CACH0:8082
    image: otpv-img
    networks:
      - app-net
volumes:
  data:
networks:
  app-net:
    driver: bridge