services:
  GPOC0:
    build:
      context: /var/lib/docker
      dockerfile: GPOC0/Dockerfile
    ports:
      - "8085:8085"
    image: gpoc-img
  IWDB0:
    build:
      context: /var/lib/docker/IWDB0/
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    image: iwdb-img
    volumes:
      - data:/var/lib/h2
  SMOC0:
    build:
      context: /var/lib/docker/SMOC0/
      dockerfile: Dockerfile
    ports:
      - "8089:8089"
    image: smoc-img
volumes:
  data: