server:
 port: 8085
  

config:
  iwdb0:
    end-point: ${IWDB0_ENDPOINT:http://localhost:8083}
  cach0:
    end-point: ${CACH0_ENDPOINT:http://localhost:8082}
  ansc0:
    end-point: ${ANSC0_ENDPOINT:http://localhost:8081}
  otpv0:
    end-point: ${OTPV0_ENDPOINT:http://localhost:8087}
  agtw0:
    end-point: ${AGTW0_ENDPOINT:http://localhost:8079}